markdown: rdiscount
pygments: true
permalink: /:title

author: Matthias Günther
email: matthias@wikimatze.de

rdiscount:
  extensions: [smart]

url: http://vimberlin.de

gems:
  - jemoji

copyright: 2014 Copyright no one at all - Vim is free.

locations:
  buero20:
    street: Weigandufer 45
    city: Berlin
    postalcode: 12059
    country: Germany
    url: http://www.buero20.org/
    map: http://www.openstreetmap.org/?lat=52.4794285&lon=13.4542985&zoom=17&layers=T&mlat=52.47952&mlon=13.45428
    name:  Büro 2.0
    addition: Conference room
  intimes:
    street: Boxhagener Str. 107
    city: Berlin
    postalcode: 10245
    country: Germany
    url:
    map: http://goo.gl/maps/a4oqk
    name: the bar Intimes
    addition:
  launchco:
    street: Warschauer Str. 70A
    city: Berlin
    postalcode: 10243
    country: Germany
    url: https://launchco.com/etc/#coworking
    map: http://g.co/maps/k62eb
    name: LAUNCH/CO
    addition: 3rd floor
  matthias:
    street: Neue Straße 6
    city: Berlin Tempelhof
    postalcode: 12103
    country: Germany
    url:
    map: http://bit.ly/To0yMf
    name: Matthias@Home
    addition:
  absolventa:
    street: Greifswalder Str. 212,
    city: Berlin
    postalcode: 10405
    country: Germany
    url: http://www.absolventa.de/
    map: http://www.openstreetmap.org/search?query=Greifswalder%20Str.%20212#map=19/52.53200/13.42776
    name: kitchen/leisure zone
    addition: ABSOLVENTA Office
  travis:
    street: Prinzessinnenstr. 20
    city: Berlin, Kreuzberg
    postalcode: 10969
    country: Germany
    url: https://travis-ci.org/
    map: http://bit.ly/1dqOIZk
    name: GanzOben Office at Betahaus (Travis CI office, 5Apps, Avarteq, Cileos)
    addition: 5th floor (<a href="https://gist.github.com/svenfuchs/5364262">detailed information how to get there</a>)
  wooga:
    street: Saarbrücker Straße 38
    city: Berlin
    postalcode: 10405
    country: Germany
    url: http://www.wooga.com/
    map: http://g.co/maps/g7tx6
    name: Wooga GmbH
    addition:
